name: Update Contribution Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install node-fetch
        run: npm install node-fetch@2
          
      - name: Create script file
        run: |
          cat > generate-contribution-stats.js << 'EOF'
          const fs = require("fs");
          const fetch = require("node-fetch");
          
          // Fetch contribution stats from API
          async function fetchStats() {
            try {
              const response = await fetch(process.env.API_URL);
              if (!response.ok) {
                throw new Error(`API responded with status: ${response.status}`);
              }
              return await response.json();
            } catch (error) {
              console.error('Error fetching stats:', error);
              throw error;
            }
          }
          
          // Format numbers with comma separators
          function formatNumber(num) {
            return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
          }
          
          // Main function to update README
          async function updateReadme() {
            try {
              // Read the README file
              const readme = fs.readFileSync('README.md', 'utf8');
              
              // Fetch stats
              const stats = await fetchStats();
              
              // Format the values for contribution stats
              const formattedContribution = {
                commits: formatNumber(stats.commits),
                issuesCreated: formatNumber(stats.issuesCreated),
                issueContrib: formatNumber(stats.issueContributions),
                prCreated: formatNumber(stats.pullRequestsCreated),
                prReviews: formatNumber(stats.pullRequestReviews),
                discussions: formatNumber(stats.discussions + stats.discussionComments)
              };
              
              // Create the formatted contribution stats block
              const contributionStatsContent = `        self.contribution_stats = { # updated ${new Date().toISOString().split('T')[0]}
            "Commits"       : ${formattedContribution.commits},
            "Issues": {
                "Created"   : ${formattedContribution.issuesCreated},
                "Contrib"   : ${formattedContribution.issueContrib},
            },
            "PR": {
                "Created"   : ${formattedContribution.prCreated},
                "Review"    : ${formattedContribution.prReviews},
            },
            "Discussions"   : ${formattedContribution.discussions},
        }`;
              
              // Define the pattern to find the contribution stats section
              const contributionStatsPattern = /(self\.contribution_stats = \{)[\s\S]*?(        \})/;
              
              // Replace the content
              const updatedReadme = readme.replace(
                contributionStatsPattern,
                contributionStatsContent
              );
              
              // Write the updated README
              fs.writeFileSync('README.md', updatedReadme);
              
              console.log('README updated successfully!');
            } catch (error) {
              console.error('Failed to update README:', error);
              process.exit(1);
            }
          }
          
          // Run the update
          updateReadme();
          EOF
      
      - name: Fetch and update README
        run: |
          # Set API URL to your deployed endpoint
          export API_URL="https://sukitsubaki.vercel.app/contribution-stats?username=sukitsubaki"
          
          # Run the Node.js script
          node generate-contribution-stats.js
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update contribution stats in README"
          git push
