name: Update Language Stats

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          npm install node-fetch@2
          
      - name: Generate Language Stats and Update README
        run: |
          # Setze Umgebungsvariablen
          export TOP_LANGUAGES=6
          
          # Fetch data from API and save to stats.json
          curl -s "https://sukitsubaki.vercel.app/language-stats" > ./stats.json
          
          # Run the formatting script
          node ./api/language-stats/func_format-stats.js
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update language stats in README"
          git push
