name: Update Language Stats (TXT)

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create script file
        run: |
          cat > generate-stats-text.js << 'EOF'
          const fs = require("fs");
          const path = require("path");
          const stats = JSON.parse(fs.readFileSync("stats.json", "utf8"));
          let readme = fs.readFileSync("README.md", "utf8");
          
          // Configuration from environment variables
          const topCount = parseInt(process.env.TOP_LANGUAGES) || 6;
          
          // Weights for calculation
          const sizeWeight = 0.6;
          const countWeight = 0.4;
          
          // Initialize language data structure
          const languages = {};
          
          // Track totals
          let totalBytes = 0;
          
          // Parse stats data
          Object.entries(stats.languages).forEach(([lang, data]) => {
            // Initialize language entry
            if (!languages[lang]) {
              languages[lang] = {
                name: lang,
                size: 0,
                count: 0,
                score: 0
              };
            }
            
            // Add byte count
            languages[lang].size = data.bytes;
            languages[lang].count = 1; // Minimum count for each language
            
            // Track totals
            totalBytes += data.bytes;
          });
          
          // Calculate weighted scores
          Object.keys(languages).forEach(lang => {
            languages[lang].score = 
              Math.pow(languages[lang].size, sizeWeight) * 
              Math.pow(languages[lang].count, countWeight);
          });
          
          // Sort languages by score and get top languages
          const sortedLanguages = Object.values(languages)
            .sort((a, b) => b.score - a.score);
            
          const topLanguages = sortedLanguages.slice(0, topCount);
          
          // Calculate total score for percentage calculation
          const totalScore = topLanguages.reduce((sum, lang) => sum + lang.score, 0);
          
          // Calculate percentages
          topLanguages.forEach(lang => {
            lang.percentage = (lang.score / totalScore) * 100;
          });
          
          // Function to create progress bar
          const createProgressBar = (percentage) => {
            const barLength = 40; // Total length of progress bar
            const filledLength = Math.round((percentage / 100) * barLength);
            const emptyLength = barLength - filledLength;
            
            // Using black blocks and dotted blocks as seen in the screenshot
            return '█'.repeat(filledLength) + '░'.repeat(emptyLength);
          };
          
          // Format file size in a human-readable way with separated number and unit
          const formatBytes = (bytes) => {
            if (bytes === 0) return ['0', 'B'];
            
            const k = 1024;
            const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
            
            const i = Math.floor(Math.log(bytes) / Math.log(k));
            
            const value = parseFloat((bytes / Math.pow(k, i)).toFixed(2));
            return [value.toString(), sizes[i]];
          };
          
          // Find the length of the longest language name
          const maxNameLength = topLanguages.reduce((max, lang) => 
            Math.max(max, lang.name.length), 0);
          
          // Generate formatted language stats
          let languageEntries = [];
          
          topLanguages.forEach((lang) => {
            // Format language name with padding
            const nameField = `"${lang.name}"`;
            
            // Calculate spaces needed for alignment
            const paddingNeeded = maxNameLength + 4 - nameField.length;
            const padding = ' '.repeat(paddingNeeded);
            
            // Progress bar
            const progressBar = createProgressBar(lang.percentage);
            
            // Format percentage
            const percentField = lang.percentage.toFixed(2).padStart(5, ' ');
            
            // Build the formatted line
            languageEntries.push(`            ${nameField}${padding}: "${progressBar}", # ${percentField} %`);
          });
          
          // Join entries with line breaks
          const formattedLanguageStats = languageEntries.join('\n');
          
          // Define the target patterns to replace in README
          const languageStatsPattern = /(self\.language_stats = \{)[\s\S]*?(        \})/;
          
          // Replace content in README
          let updatedReadme = readme.replace(
            languageStatsPattern, 
            `$1\n${formattedLanguageStats}\n$2`
          );
          
          // Write updated README
          fs.writeFileSync("README.md", updatedReadme);
          EOF
      
      - name: Generate Language Stats Text and Update README
        run: |
          # Configuration
          export TOP_LANGUAGES=6      # Show top 6 languages
          
          # Fetch the API and save results
          curl -s "https://sukitsubaki.vercel.app/language-stats" > stats.json
          
          # Run the Node.js script
          node generate-stats-text.js
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update language stats in README"
          git push
