name: Update Contribution Stats

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install node-fetch
        run: npm install node-fetch@2
          
      - name: Run contribution stats script
        run: |
          export API_URL="https://sukitsubaki.vercel.app/contribution-stats"
          node ./api/contribution-stats/func_format-stats.js
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update contribution stats in README"
          git push
