name: Update Language Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Download script file
        run: |
          curl -o generate-stats-text.js https://raw.githubusercontent.com/sukitsubaki/sukitsubaki/main/scripts/generate-stats-text.js
      
      - name: Generate Language Stats Text and Update README
        run: |
          export TOP_LANGUAGES=6
          curl -s "https://sukitsubaki.vercel.app/language-stats" > stats.json
          node generate-stats-text.js
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update language stats in README"
          git push
