name: Update Profile Views

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install node-fetch
        run: npm install node-fetch@2
          
      - name: Run profile views script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_URL: "https://sukitsubaki.vercel.app/profile-views"
        run: node ./api/profile-views/func_format-stats.js
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git add api/profile-views/profile-views.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update profile views in README"
          git push
