name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Update README with Language Stats
        run: |
          # Fetch the API and save results
          curl -s "https://deine-vercel-url.vercel.app/language-stats" > stats.json
          
          # Generate the new README with language statistics
          node -e '
            const fs = require("fs");
            const stats = JSON.parse(fs.readFileSync("stats.json", "utf8"));
            let readme = fs.readFileSync("README.md", "utf8");
            
            // Create the language stats section
            let langSection = "## My Programming Languages\n\n";
            
            // Add top 5 languages
            Object.entries(stats.languages)
              .slice(0, 5)
              .forEach(([lang, data]) => {
                langSection += `- ${lang}: ${data.percentage}\n`;
              });
            
            // Add a note about weighting
            langSection += "\n*Statistics based on all my repositories with 50/50 weighting between bytes and file count.*";
            
            // Replace existing section or append to the end
            const startMarker = "<!-- START_LANGUAGE_STATS -->";
            const endMarker = "<!-- END_LANGUAGE_STATS -->";
            
            if (readme.includes(startMarker) && readme.includes(endMarker)) {
              // Replace existing section
              const regex = new RegExp(`${startMarker}[\\s\\S]*?${endMarker}`, "g");
              readme = readme.replace(regex, `${startMarker}\n${langSection}\n${endMarker}`);
            } else {
              // Append at the end
              readme += `\n\n${startMarker}\n${langSection}\n${endMarker}`;
            }
            
            fs.writeFileSync("README.md", readme);
          '
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update language stats in README"
          git push
